# Generated by Django 3.2.4 on 2021-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_name', models.CharField(max_length=30)),
                ('another_id', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Anothers',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('apartment_id', models.IntegerField()),
            ],
        ),
    ]
