# Generated by Django 3.2.4 on 2021-06-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testmodel',
            unique_together={('name', 'apartment_id')},
        ),
    ]
